---
# Manage static Galaxy configuration files

- name: Create Galaxy config and shed tools directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ galaxy_config_dir }}"
    - "{{ galaxy_shed_tools_dir }}"

- name: Install additional Galaxy config files (static)
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  with_items: "{{ galaxy_config_files }}"

- name: Install additional Galaxy config files (template)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  with_items: "{{ galaxy_config_templates }}"

- name: Create Galaxy configuration file
  template:
    src: "{{ galaxy_config_file_template }}"
    dest: "{{ galaxy_config_file }}"
    backup: yes
  notify:
    - restart galaxy

- name: Create Galaxy tool sheds configuration file
  template:
    src: "{{ tool_sheds_config_file_template }}"
    dest: "{{ tool_sheds_config_file }}"
    mode: 0644
    backup: yes
  notify:
    - restart galaxy
  when: galaxy_tool_sheds_config

- name: Set path to tool sheds configuration file
  lineinfile:
    path: "{{ galaxy_config_file }}"
    regexp: "^    tool_sheds_config_file: "
    line: "    tool_sheds_config_file: {{ tool_sheds_config_file }}"
  when: galaxy_tool_sheds_config
